import {Inter} from 'next/font/google'
import './globals.css'
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";
import {ThemeProvider} from "../context/ThemeContext";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'AI',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider>
                    <div className="container">
                        <Navbar/>
                        {children}
                        <Footer/>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}
